FROM jenkins/jenkins:lts

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing && \
    apt-get install -y docker.io make g++ curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins

